"""VenvStudio - Package Panel: Export Mixin
Export installed packages to requirements.txt, Dockerfile, pyproject.toml,
conda env.yml, clipboard, or import requirements (moved from package_panel.py).
"""
import os
import sys
import subprocess
from pathlib import Path

from PySide6.QtWidgets import QFileDialog, QMessageBox

from src.utils.i18n import tr
from src.utils.platform_utils import get_platform, get_python_executable, subprocess_args
from src.utils.constants import COMMAND_HINTS
from src.gui.package_panel_common import WorkerThread


class PackageExportMixin:
    """Mixin for PackagePanel: export/import package lists."""

    def _export_requirements(self):
        if not self.pip_manager:
            return
        filepath, _ = QFileDialog.getSaveFileName(
            self, "Export Requirements", "requirements.txt", "Text Files (*.txt)"
        )
        if filepath:
            success, msg = self.pip_manager.export_requirements(Path(filepath))
            self._show_command_hint("Export Requirements", {
                "venv": "pip freeze > requirements.txt",
                "uv": "uv pip freeze > requirements.txt",
                "poetry": "poetry export -f requirements.txt",
                "conda": "conda list --export > requirements.txt",
            }.get(getattr(self, "_current_env_type", "venv"), COMMAND_HINTS["freeze"]))
            if success:
                QMessageBox.information(self, "Success", msg)
            else:
                QMessageBox.critical(self, "Error", msg)

    def _get_freeze_and_version(self):
        """Helper: get freeze content and python version for export."""
        if not self.pip_manager:
            QMessageBox.warning(self, "Warning", "No environment selected.")
            return None, None
        freeze = self.pip_manager.freeze()
        if not freeze:
            QMessageBox.warning(self, "Warning", "No packages to export.")
            return None, None
        # Get python version
        py_ver = "3.12"
        try:
            python_exe = get_python_executable(self.pip_manager.venv_path)
            result = subprocess.run(
                [str(python_exe), "--version"],
                capture_output=True, text=True, timeout=10,
                **subprocess_args()
            )
            ver_text = (result.stdout.strip() or result.stderr.strip()).replace("Python ", "")
            py_ver = ".".join(ver_text.split(".")[:2])  # "3.14"
        except Exception:
            pass
        return freeze, py_ver

    def _export_dockerfile(self):
        """Export as Dockerfile."""
        freeze, py_ver = self._get_freeze_and_version()
        if not freeze:
            return

        packages = [line.strip() for line in freeze.strip().splitlines() if line.strip() and not line.startswith("#")]

        dockerfile = f"""# Auto-generated by VenvStudio
FROM python:{py_ver}-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Run application
# CMD ["python", "main.py"]
"""

        filepath, _ = QFileDialog.getSaveFileName(
            self, "Export Dockerfile", "Dockerfile", "All Files (*)"
        )
        if filepath:
            # Also save requirements.txt alongside
            req_path = Path(filepath).parent / "requirements.txt"
            try:
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(dockerfile)
                with open(req_path, "w", encoding="utf-8") as f:
                    f.write(freeze)
                QMessageBox.information(
                    self, "✅ Success",
                    f"Exported:\n  📄 {filepath}\n  📄 {req_path}\n\n"
                    f"Build with:\n  docker build -t myapp ."
                )
            except IOError as e:
                QMessageBox.critical(self, "Error", str(e))

    def _export_docker_compose(self):
        """Export as docker-compose.yml + Dockerfile."""
        freeze, py_ver = self._get_freeze_and_version()
        if not freeze:
            return

        compose = f"""# Auto-generated by VenvStudio
version: '3.8'

services:
  app:
    build: .
    container_name: myapp
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    # command: python main.py
"""

        dockerfile = f"""# Auto-generated by VenvStudio
FROM python:{py_ver}-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# CMD ["python", "main.py"]
"""

        filepath, _ = QFileDialog.getSaveFileName(
            self, "Export docker-compose.yml", "docker-compose.yml", "YAML Files (*.yml);;All Files (*)"
        )
        if filepath:
            base_dir = Path(filepath).parent
            try:
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(compose)
                with open(base_dir / "Dockerfile", "w", encoding="utf-8") as f:
                    f.write(dockerfile)
                with open(base_dir / "requirements.txt", "w", encoding="utf-8") as f:
                    f.write(freeze)
                QMessageBox.information(
                    self, "✅ Success",
                    f"Exported:\n"
                    f"  📄 {filepath}\n"
                    f"  📄 {base_dir / 'Dockerfile'}\n"
                    f"  📄 {base_dir / 'requirements.txt'}\n\n"
                    f"Run with:\n  docker-compose up --build"
                )
            except IOError as e:
                QMessageBox.critical(self, "Error", str(e))

    def _export_pyproject(self):
        """Export as pyproject.toml."""
        freeze, py_ver = self._get_freeze_and_version()
        if not freeze:
            return

        packages = []
        for line in freeze.strip().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                packages.append(f'    "{line}",')

        deps_str = "\n".join(packages)

        pyproject = f"""# Auto-generated by VenvStudio
[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "myproject"
version = "0.1.0"
description = ""
requires-python = ">={py_ver}"
dependencies = [
{deps_str}
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
]
"""

        filepath, _ = QFileDialog.getSaveFileName(
            self, "Export pyproject.toml", "pyproject.toml", "TOML Files (*.toml);;All Files (*)"
        )
        if filepath:
            try:
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(pyproject)
                QMessageBox.information(self, "✅ Success", f"Exported to:\n{filepath}")
            except IOError as e:
                QMessageBox.critical(self, "Error", str(e))

    def _export_conda_yml(self):
        """Export as Conda environment.yml."""
        freeze, py_ver = self._get_freeze_and_version()
        if not freeze:
            return

        pip_packages = []
        for line in freeze.strip().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                pip_packages.append(f"    - {line}")

        pip_str = "\n".join(pip_packages)

        conda_yml = f"""# Auto-generated by VenvStudio
name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python={py_ver}
  - pip
  - pip:
{pip_str}
"""

        filepath, _ = QFileDialog.getSaveFileName(
            self, "Export environment.yml", "environment.yml", "YAML Files (*.yml);;All Files (*)"
        )
        if filepath:
            try:
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(conda_yml)
                QMessageBox.information(
                    self, "✅ Success",
                    f"Exported to:\n{filepath}\n\n"
                    f"Create with:\n  conda env create -f environment.yml"
                )
            except IOError as e:
                QMessageBox.critical(self, "Error", str(e))

    def _export_clipboard(self):
        """Copy freeze output to clipboard."""
        if not self.pip_manager:
            QMessageBox.warning(self, "Warning", "No environment selected.")
            return
        freeze = self.pip_manager.freeze()
        if not freeze:
            QMessageBox.warning(self, "Warning", "No packages to export.")
            return
        from PySide6.QtWidgets import QApplication
        QApplication.clipboard().setText(freeze)
        self.status_label.setText("📋 Package list copied to clipboard!")
        QMessageBox.information(
            self, "✅ Copied",
            f"Copied {len(freeze.strip().splitlines())} packages to clipboard."
        )

    def _import_requirements(self):
        if not self.pip_manager:
            QMessageBox.warning(self, "Warning", "No environment selected.")
            return
        filepath, _ = QFileDialog.getOpenFileName(
            self, "Import Requirements", "", "Text Files (*.txt);;All Files (*)"
        )
        if filepath:
            self._show_command_hint("Import Requirements", {
                "venv": "pip install -r requirements.txt",
                "uv": "uv pip install -r requirements.txt",
                "poetry": "poetry install",
                "conda": "conda install --file requirements.txt",
            }.get(getattr(self, "_current_env_type", "venv"), COMMAND_HINTS["import_req"]))
            self._set_busy(True)
            self.current_worker = WorkerThread(
                self.pip_manager.import_requirements, Path(filepath)
            )
            self.current_worker.progress.connect(self._on_progress)
            self.current_worker.finished.connect(self._on_install_finished)
            self.current_worker.start()

